name: Build Starting..

on: 
  #releasepush:
    #pushbuild

  watch: 
      types: [started]
    
env:              #change ROM_URL,ROM_NAME,ZIP_NAME,ROMZIP_NAME respectivley. ROM_NAME is case sensitive 
  ROM_URL: https://mva1.androidfilehost.com/dl/ChFOsTQd_iUjNK_E6tj8Ug/1604573894/10763459528675577265/PixelExperience_ginkgo-10.0-20201103-1023-FireBuild.zip
  ROM_NAME: Pixel:PixelExperience
  ZIP_NAME: PixelExperience10
  SECRETS_PASSWORD: ${{ secrets.SFGPASS }}
  TZ: Middle-East/Kuwait
  SFDIRA1: cd /home/pfs/project/berkay-gsi/PixelExperience
  SFDIRA2: cd /home/pfs/project/berkay-gsi/berkay
  SFUSER: ${{ secrets.SFUSER }}

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Configuring settings
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt-get install -y expect
            
                 
       - name: Downloading Erfan Repo
         run: git clone ${{ secrets.ERFAN }}
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Downloading Rom
         run: cd ErfanGSIs && sudo ./url2GSI.sh $ROM_URL $ROM_NAME 
     
                       
       - name: Zipping..
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img 
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
       - name: Uploading SourceForge
         run: |   
              cd ErfanGSIs/output
              expect -c " 
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA2\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"  
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
